### ISSUE TITLE
Error at install when reading the readme

### ISSUE THREAD

**Issue by Kristopher38** [xmpppy/xmpppy#46]
OS: Windows 7
Python: 3.7.1
xmpppy version: latest (0.6.2)

Installation errors out when trying to read the readme:
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Krzychu\AppData\Local\Temp\pip-install-w0qmfaz6\xmpppy_b4e34b41ffb641f68c7cf59cda30c9a2\setup.py", line 6, in <module>
        README = open(os.path.join(here, 'README.rst')).read()
      File "c:\users\krzychu\appdata\local\programs\python\python37\lib\encodings\cp1250.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1087: character maps to <undefined>
```
The issue is the ☠ character - removing all occurences in the readme fixes the problem.

**Comment by Brewsk11** [comment]
I can confirm this is an issue on:
OS: Windows 10
Python: 3.9.6
xmpppy version: 0.6.2

Came across this when installing [apqlzm/medihunter](https://github.com/apqlzm/medihunter).

**Comment by amotl** [comment]
Dear Kristopher and Paweł,

thank you for reporting this and apologies for the delay. I've just removed those special characters from the README file and released xmpppy version 0.6.3 to PyPI. Let me know if that works for you.

With kind regards,
Andreas.
