### ISSUE TITLE
method send from Client class is not found

### ISSUE THREAD

**Issue by bloccato** [xmpppy/xmpppy#66]
Hi! I'm writing some code with this library and the send() method is not found for the Client class, how to solve that?

**Comment by amotl** [comment]
Dear Lorenzo,

thank you for writing in. I am not 100% sure, but I think the `send()` method is implemented in the transport class [1]. It probably gets mixed into the `Client` class by using xmpppy's Plugin subsystem [2] at runtime.

If you observe any problems using the library, feel free to share your code, and eventual error messages, for example, tracebacks, in text format. Please do not send screenshots.

With kind regards,
Andreas.

[1] https://github.com/xmpppy/xmpppy/blob/dbb35f508a1ead5c3c5ad6ea8954da4d28fdd825/xmpp/transports.py#L222-L246
[2] https://github.com/xmpppy/xmpppy/blob/dbb35f508a1ead5c3c5ad6ea8954da4d28fdd825/xmpp/client.py#L53-L88

**Comment by bloccato** [comment]
I don't get any error message. I actually don't know how to implement the `send` method in my code. I tried everything

**Comment by amotl** [comment]
Maybe you can use the command-line [3] more successful? Its implementation can be found at [4].

[3] https://github.com/xmpppy/xmpppy#command-line-interface
[4] https://github.com/xmpppy/xmpppy/blob/dbb35f508a1ead5c3c5ad6ea8954da4d28fdd825/xmpp/cli.py#L17-L31

**Comment by bloccato** [comment]
`connection.send` is not working

**Comment by amotl** [comment]
Hi again,

with GH-67, I've just improved the README a bit. The code example will now work out of the box when, for example, run on a Python REPL. This looks like that:
```
(.venv) sink:xmpppy amo$ python
Python 3.9.16 (main, Mar 15 2023, 23:33:53)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmpp
>>>
>>> jabberid = "foobar@xmpp.domain.tld"
>>> password = "secret"
>>> receiver = "bazqux@xmpp.domain.tld"
>>> message  = "hello world"
>>>
>>> def main():
...     jid = xmpp.protocol.JID(jabberid)
...     connection = xmpp.Client(server=jid.getDomain(), debug=True)
...     connection.connect()
...     connection.auth(user=jid.getNode(), password=password, resource=jid.getResource())
...     connection.send(xmpp.protocol.Message(to=receiver, body=message))
...
>>> if __name__ == "__main__":
...     main()
...
Invalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG:
DEBUG: Debug created for /Users/amo/dev/foss/xmpppy/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket object at 0x106f99f40> into <xmpp.client.Client object at 0x106f99fd0>
DEBUG: socket       warn  Could not load one of the supported DNS libraries (dnspython or pydns). SRV records will not be queried and you may need to set custom hostname/port for some servers to be accessible.\n
DEBUG: socket       error Failed to lookup remote host ('xmpp.domain.tld', 5222): nodename nor servname provided, or not known (8)
Traceback (most recent call last):
  File "/Users/amo/dev/foss/xmpppy/xmpp/transports.py", line 156, in connect
    for res in socket.getaddrinfo(server[0], int(server[1]), 0, socket.SOCK_STREAM):
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
DEBUG: socket       stop  Plugging <xmpp.transports.TCPsocket object at 0x106f99f40> out of <xmpp.client.Client object at 0x106f99fd0>.
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "<stdin>", line 4, in main
  File "/Users/amo/dev/foss/xmpppy/xmpp/client.py", line 203, in connect
    if not CommonClient.connect(self,server,proxy,secure,use_srv,transport) or secure!=None and not secure: return self.connected
  File "/Users/amo/dev/foss/xmpppy/xmpp/client.py", line 175, in connect
    sock.PlugOut()
  File "/Users/amo/dev/foss/xmpppy/xmpp/client.py", line 79, in PlugOut
    if 'plugout' in self.__class__.__dict__: ret = self.plugout()
  File "/Users/amo/dev/foss/xmpppy/xmpp/transports.py", line 178, in plugout
    self._sock.close()
AttributeError: 'TCPsocket' object has no attribute '_sock'
```

So, in all humbleness, "it is not working" is not a good way to _express_ that it is not working in a bug tracker, and maybe beyond. Can you come up with something more meaningful how to solve your problem. For example, can you outline _how_ you are aiming to make `connection.send()` work, for example by sharing the code you are using for that?

If it is part of a larger system you are working on, it might be sensible to start with small examples that work, in order to discover the root cause of the problem at hand. You may want to use the code example shared at [5], run it on a Python REPL, and share the outcome back with us.

With kind regards,
Andreas.

[5] https://github.com/xmpppy/xmpppy#as-a-library

**Comment by bloccato** [comment]
I use this code

```python
def main():
    jid = xmpp.protocol.JID("jid")
    connection = xmpp.Client(server=jid.getDomain(), debug=True)
    connection.connect(server=("server", 5222))
    connection.auth(user="user", password="password", resource=jid.getResource())
    message = xmpp.Message(to="recipeint", body="hi")
    message.setNamespace(None)
    message.setAttr("type", "chat")
    message.setTag(name="c", namespace="c2m:c")
    message.setTagData(tag="c", val="579007379188829483")
    connection.send(message)
```

the method send is not found for the variable connection

**Comment by amotl** [comment]
> the method send is not found for the variable connection

You are not referring to those admonitions by modern code editors, or corresponding linter warnings, right?

![image](https://github.com/xmpppy/xmpppy/assets/453543/639383cc-2b16-4964-8faf-accfd6f71a1a)

If that is the case, the reasons why this happens is outlined at https://github.com/xmpppy/xmpppy/issues/66#issuecomment-1548231435. It should not be of much concern, unless you use those tools on this code base. This, on the other hand, I would humbly discourage, because it does not adhere to any modern Python coding standards.

**Comment by bloccato** [comment]
> Thank you. I've modified your code example slightly on a few spots, and verified it works fully and thoroughly well with the Jabber server I am using. Can I humbly ask you to run that example on your Jabber server, and report back about the outcome, including output?
> 
> ```python
> import xmpp
> 
> 
> jabberid = "foobar@xmpp.domain.tld"
> password = "secret"
> recipient = "bazqux@xmpp.domain.tld"
> message  = "hello world"
> 
> 
> def main():
>     jid = xmpp.protocol.JID(jabberid)
>     connection = xmpp.Client(server=jid.getDomain(), debug=True)
>     connection.connect()
>     connection.auth(user=jid.getNode(), password=password, resource=jid.getResource())
>     xmsg = xmpp.Message(to=recipient, body=message)
>     xmsg.setNamespace(None)
>     xmsg.setAttr("type", "chat")
>     xmsg.setTag(name="c", namespace="c2m:c")
>     xmsg.setTagData(tag="c", val="579007379188829483")
>     connection.send(xmsg)
> 
> 
> if __name__ == "__main__":
>     main()
> ```

I don't run it on a Jabber server, I'm trying to connect on a remote server

**Comment by bloccato** [comment]
`
nvalid debugflag given: always
Invalid debugflag given: nodebuilder
DEBUG: 
DEBUG: Debug created for /home/lorenzo/.local/lib/python3.8/site-packages/xmpp/client.py
DEBUG:  flags defined: always,nodebuilder
DEBUG: socket       start Plugging <xmpp.transports.TCPsocket object at 0x7f8829da4e20> into <xmpp.client.Client object at 0x7f8829da4fd0>
DEBUG: socket       warn  Could not load one of the supported DNS libraries (dnspython or pydns). SRV records will not be queried and you may need to set custom hostname/port for some servers to be accessible.\n
DEBUG: socket       start Successfully connected to remote host ('x.connected2.me', 5222)
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher object at 0x7f8829da4f10> into <xmpp.client.Client object at 0x7f8829da4fd0>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as <class 'xmpp.protocol.Iq'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as <class 'xmpp.protocol.Presence'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as <class 'xmpp.protocol.Message'>(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher object at 0x7f8829da4f10>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" to="x.connected2.me" >
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='5830119313464868689' from='x.connected2.me' version='1.0' xml:lang='en'>
DEBUG: socket       got   <stream:features>
  <c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='YkF9wivV3RXIfavSzmqe0EJU4gQ='/>
  <register xmlns='http://jabber.org/features/iq-register'/>
  <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
  <mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
  <mechanism>PLAIN</mechanism>
  <mechanism>X-OAUTH2</mechanism>
  </mechanisms>
  </stream:features>
DEBUG: dispatcher   warn  Unknown stanza: features
DEBUG: dispatcher   ok    Dispatching unknown stanza with type-> props->['http://jabber.org/protocol/caps', 'http://jabber.org/features/iq-register', 'urn:ietf:params:xml:ns:xmpp-tls', 'urn:ietf:params:xml:ns:xmpp-sasl'] id->None
DEBUG: tls          start Plugging <xmpp.transports.TLS object at 0x7f8829d614c0> into <xmpp.client.Client object at 0x7f8829da4fd0>
DEBUG: tls          ok    TLS supported by remote server. Requesting TLS start.
DEBUG: dispatcher   info  Registering handler <bound method TLS.StartTLSHandler of <xmpp.transports.TLS object at 0x7f8829d614c0>> for "proceed" type-> ns->(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   warn  Registering namespace "urn:ietf:params:xml:ns:xmpp-tls"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   warn  Registering protocol "proceed" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   info  Registering handler <bound method TLS.StartTLSHandler of <xmpp.transports.TLS object at 0x7f8829d614c0>> for "failure" type-> ns->(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: dispatcher   warn  Registering protocol "failure" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-tls)
DEBUG: socket       sent  <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>
DEBUG: socket       got   <proceed xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-tls/proceed stanza
DEBUG: dispatcher   ok    Dispatching proceed stanza with type-> props->[] id->None
DEBUG: tls          ok    Got starttls proceed response. Switching to TLS/SSL...
DEBUG: dispatcher   stop  Plugging <xmpp.dispatcher.Dispatcher object at 0x7f8829da4f10> out of <xmpp.client.Client object at 0x7f8829da4fd0>.
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher object at 0x7f8829d615b0> into <xmpp.client.Client object at 0x7f8829da4fd0>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as <class 'xmpp.protocol.Iq'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as <class 'xmpp.protocol.Presence'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as <class 'xmpp.protocol.Message'>(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher object at 0x7f8829d615b0>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" to="x.connected2.me" >
DEBUG: socket       warn  SSL_WANT_READ while receiving data, asking for a retry
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='3737854082724551149' from='x.connected2.me' version='1.0' xml:lang='en'>
DEBUG: socket       warn  SSL_WANT_READ while receiving data, asking for a retry
DEBUG: socket       got   <stream:features>
  <c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='YkF9wivV3RXIfavSzmqe0EJU4gQ='/>
  <register xmlns='http://jabber.org/features/iq-register'/>
  <mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
  <mechanism>PLAIN</mechanism>
  <mechanism>X-OAUTH2</mechanism>
  </mechanisms>
  </stream:features>
DEBUG: dispatcher   warn  Unknown stanza: features
DEBUG: dispatcher   ok    Dispatching unknown stanza with type-> props->['http://jabber.org/protocol/caps', 'http://jabber.org/features/iq-register', 'urn:ietf:params:xml:ns:xmpp-sasl'] id->None
DEBUG: sasl         start Plugging <xmpp.auth.SASL object at 0x7f8829d61820> into <xmpp.client.Client object at 0x7f8829da4fd0>
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL object at 0x7f8829d61820>> for "challenge" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering namespace "urn:ietf:params:xml:ns:xmpp-sasl"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "challenge" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL object at 0x7f8829d61820>> for "failure" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "failure" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   info  Registering handler <bound method SASL.SASLHandler of <xmpp.auth.SASL object at 0x7f8829d61820>> for "success" type-> ns->(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: dispatcher   warn  Registering protocol "success" as <class 'xmpp.protocol.Protocol'>(urn:ietf:params:xml:ns:xmpp-sasl)
DEBUG: socket       sent  <auth xmlns="urn:ietf:params:xml:ns:xmpp-sasl" mechanism="PLAIN">dXd1bG9sekB4LmNvbm5lY3RlZDIubWUAdXd1bG9segBVc2VyMzQ2NyE=</auth>
DEBUG: socket       warn  SSL_WANT_READ while receiving data, asking for a retry
DEBUG: socket       got   <success xmlns='urn:ietf:params:xml:ns:xmpp-sasl'/>
DEBUG: dispatcher   ok    Got urn:ietf:params:xml:ns:xmpp-sasl/success stanza
DEBUG: dispatcher   ok    Dispatching success stanza with type-> props->[] id->None
DEBUG: sasl         ok    Successfully authenticated with remote server.
DEBUG: dispatcher   stop  Plugging <xmpp.dispatcher.Dispatcher object at 0x7f8829d615b0> out of <xmpp.client.Client object at 0x7f8829da4fd0>.
DEBUG: dispatcher   start Plugging <xmpp.dispatcher.Dispatcher object at 0x7f8829d61910> into <xmpp.client.Client object at 0x7f8829da4fd0>
DEBUG: dispatcher   info  Registering namespace "unknown"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(unknown)
DEBUG: dispatcher   info  Registering namespace "http://etherx.jabber.org/streams"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: dispatcher   info  Registering namespace "jabber:client"
DEBUG: dispatcher   info  Registering protocol "unknown" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "default" as <class 'xmpp.protocol.Protocol'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "iq" as <class 'xmpp.protocol.Iq'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "presence" as <class 'xmpp.protocol.Presence'>(jabber:client)
DEBUG: dispatcher   info  Registering protocol "message" as <class 'xmpp.protocol.Message'>(jabber:client)
DEBUG: dispatcher   info  Registering handler <bound method Dispatcher.streamErrorHandler of <xmpp.dispatcher.Dispatcher object at 0x7f8829d61910>> for "error" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "error" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       sent  <?xml version='1.0'?>
  <stream:stream xmlns="jabber:client" version="1.0" xmlns:stream="http://etherx.jabber.org/streams" to="x.connected2.me" >
DEBUG: bind         start Plugging <xmpp.auth.Bind object at 0x7f8829d618b0> into <xmpp.client.Client object at 0x7f8829da4fd0>
DEBUG: dispatcher   info  Registering handler <bound method Bind.FeaturesHandler of <xmpp.auth.Bind object at 0x7f8829d618b0>> for "features" type-> ns->(http://etherx.jabber.org/streams)
DEBUG: dispatcher   warn  Registering protocol "features" as <class 'xmpp.protocol.Protocol'>(http://etherx.jabber.org/streams)
DEBUG: socket       warn  SSL_WANT_READ while receiving data, asking for a retry
DEBUG: socket       got   <?xml version='1.0'?>
  <stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='14948497663243169813' from='x.connected2.me' version='1.0' xml:lang='en'>
DEBUG: socket       warn  SSL_WANT_READ while receiving data, asking for a retry
DEBUG: socket       got   <stream:features>
  <c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='YkF9wivV3RXIfavSzmqe0EJU4gQ='/>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'/>
  <session xmlns='urn:ietf:params:xml:ns:xmpp-session'>
  <optional/>
  </session>
  <sm xmlns='urn:xmpp:sm:2'/>
  <sm xmlns='urn:xmpp:sm:3'/>
  <csi xmlns='urn:xmpp:csi:0'/>
  </stream:features>
DEBUG: dispatcher   ok    Got http://etherx.jabber.org/streams/features stanza
DEBUG: dispatcher   ok    Dispatching features stanza with type-> props->['http://jabber.org/protocol/caps', 'urn:ietf:params:xml:ns:xmpp-bind', 'urn:ietf:params:xml:ns:xmpp-session', 'urn:xmpp:sm:2', 'urn:xmpp:sm:3', 'urn:xmpp:csi:0'] id->None
DEBUG: socket       sent  <iq type="set" id="5">
  <bind xmlns="urn:ietf:params:xml:ns:xmpp-bind" />
  </iq>
DEBUG: dispatcher   wait  Waiting for ID:5 with timeout 25...
DEBUG: socket       warn  SSL_WANT_READ while receiving data, asking for a retry
DEBUG: socket       got   <iq id='5' type='result'>
  <bind xmlns='urn:ietf:params:xml:ns:xmpp-bind'>
  <jid>uwulolz@x.connected2.me/8158920542372034735524582410</jid>
  </bind>
  </iq>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->result props->['urn:ietf:params:xml:ns:xmpp-bind'] id->5
DEBUG: dispatcher   ok    Expected stanza arrived!
DEBUG: bind         ok    Successfully bound uwulolz@x.connected2.me/8158920542372034735524582410.
DEBUG: socket       sent  <iq type="set" id="6">
  <session xmlns="urn:ietf:params:xml:ns:xmpp-session" />
  </iq>
DEBUG: dispatcher   wait  Waiting for ID:6 with timeout 25...
DEBUG: socket       warn  SSL_WANT_READ while receiving data, asking for a retry
DEBUG: socket       got   <iq type='result' id='6'/>
DEBUG: dispatcher   ok    Got jabber:client/iq stanza
DEBUG: dispatcher   ok    Dispatching iq stanza with type->result props->[] id->6
DEBUG: dispatcher   ok    Expected stanza arrived!
DEBUG: bind         ok    Successfully opened session.
DEBUG: socket       sent  <message to="AuroraHK4@x.connected2.me" type="chat" id="7">
  <body>ciao</body>
  <c xmlns="c2m:c">579007379188829483</c>
  </message>
`

this is the output

**Comment by amotl** [comment]
Dear Lorenzo,

the output looks exactly how it looks for me, and reflects that the message has been submitted correctly. It should have worked now.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Lorenzo,

have you been successful to submit an XMPP message in the meanwhile? I can't spot any serious error in the log output you've shared.

With kind regards,
Andreas.
